### ISSUE TITLE
Software freedom

### ISSUE THREAD

**Issue by McSinyx** [opendreamnet/dreamlink.cloud#13]
Hi, the idea of spawning an JS IPFS node as needed is awesome and would greatly help the adoption of IPFS by end users.  Would you consider releasing this implementation under a free software license to even better help the ecosystem?  I'd personally recommend AGPLv3+, which will forever ensure that the software will remain libre.

**Comment by kolessios** [comment]
Hi, DreamLink uses a MIT library that I have created to handle various IPFS functions more easily and with an API similar to [webtorrent](https://github.com/webtorrent/webtorrent):

https://www.npmjs.com/package/@opendreamnet/ipfs [(Source code)](https://github.com/dreamnettech/monorepo/tree/master/workspaces/ipfs).

Just keep in mind that for now there is no documentation or tests, so I can not guarantee its proper functioning in any scenario.

Until I make the documentation of the libraries and the web site, for now I recommend you to see the **Typescript types** and the following files:

- [Starting the node.](https://github.com/opendreamnet/dreamlink.cloud/blob/master/modules/ipfs.ts)
- [Adding a CID and obtaining a `Record` with metadata and other functions.](https://github.com/opendreamnet/dreamlink.cloud/blob/master/mixins/NetworkObject.ts#L28)
- [Uploading files.](https://github.com/opendreamnet/dreamlink.cloud/blob/master/pages/index.vue#L84)

**Comment by McSinyx** [comment]
I think I wasn't clear, I wanted dreamlink.cloud to be released under a free software license so that I can comfortably recommend it to others.  Personally I am not interested in deriving or using the site because I have a go-ipfs node running locally on all of my machines, but most people in my circle don't.  The only thing preventing me from suggesting this is that it is not explicitly released under a libre license, and thus fallback to the default *all right reserved* and goes against my ethical standard.

**Comment by kolessios** [comment]
Sorry for the confusion, the next version will be released under the AGPLv3+ license. 👍

**Comment by McSinyx** [comment]
Thanks, this is awesome!  BTW I notice that you used the markdown file extension for the license text: [GitHub will pick that up and ill-rendered it](https://github.com/opendreamnet/dreamlink.cloud/blob/master/LICENSE.md).  I suggest renaming it to `LICENSE`.
