### ISSUE TITLE
Cannot upload a file which bigger than 262KB

### ISSUE THREAD

**Issue by linkerlin** [opendreamnet/dreamlink.cloud#40]
Why？

**Comment by kolessios** [comment]
Have you tried from another web browser? Depending on your operating system and web browser there may be a local storage limit.

**Comment by linkerlin** [comment]
> Have you tried from another web browser? Depending on your operating system and web browser there may be a local storage limit.

I tried edge/chrome/firefox/safari and got the same result: file size has a 262KB limited

**Comment by linkerlin** [comment]
> > Have you tried from another web browser? Depending on your operating system and web browser there may be a local storage limit.
> 
> I tried edge/chrome/firefox/safari and got the same result: file size has a 262KB limited

upload a big folder is ok

**Comment by linkerlin** [comment]
> > Have you tried from another web browser? Depending on your operating system and web browser there may be a local storage limit.
> 
> I tried edge/chrome/firefox/safari and got the same result: file size has a 262KB limited

https://bafybeibbx7miptsdd3hrrntu4qnkbrsupfxc4sjgs43v6f5t7bwht4ytzq.ipfs.dweb.link/explorer?cid=QmSeND2U7sH5E2kn1F468vM7qmD1okStvs6W8b89ZL7jVm&name=00020.png

**Comment by linkerlin** [comment]
> > > Have you tried from another web browser? Depending on your operating system and web browser there may be a local storage limit.
> > 
> > 
> > I tried edge/chrome/firefox/safari and got the same result: file size has a 262KB limited
> 
> https://bafybeibbx7miptsdd3hrrntu4qnkbrsupfxc4sjgs43v6f5t7bwht4ytzq.ipfs.dweb.link/explorer?cid=QmSeND2U7sH5E2kn1F468vM7qmD1okStvs6W8b89ZL7jVm&name=00020.png

upload a big png,but got only 262KB

**Comment by linkerlin** [comment]
![image](https://user-images.githubusercontent.com/37062/224865499-510dca47-f2ae-48b1-83fc-b40b7453a0ed.png)

**Comment by linkerlin** [comment]
Tried another file and got the same limit(262KB)
https://www.dreamlink.cloud/explorer?cid=QmT3DajPV2UxZnvdvEo4vNNEuuf6eUFKi5YksDtbrjw4Pi&name=00010%20%281%29.png

**Comment by linkerlin** [comment]
https://gateway.ipfs.io[/ipfs/QmZP3mzWBPkvDXxXT3tzsjezoQSmRcJ7vNPLrCxDpYfAJL/](https://gateway.ipfs.io/ipfs/QmZP3mzWBPkvDXxXT3tzsjezoQSmRcJ7vNPLrCxDpYfAJL/?filename=2023-03-13)?filename=2023-03-13
files in the folder is broken , all files' size is limited to 262KB
https://www.dreamlink.cloud/explorer?cid=QmZP3mzWBPkvDXxXT3tzsjezoQSmRcJ7vNPLrCxDpYfAJL&name=2023-03-13
![image](https://user-images.githubusercontent.com/37062/224866487-e186c38d-5f09-4d5a-9a9a-b75f3b2fbaf9.png)

**Comment by kolessios** [comment]
Thank you very much for the report, I have recently updated the project dependencies and it seems that the problem has been fixed.

- https://www.dreamlink.cloud/
- ipfs://bafybeieu4dfc3zzjjmgu7c3lqouohxiolkir6wkaeblt3d46y3kjc55evm
